// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vncpvmndkdzcdberruxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuY3B2bW5ka2R6Y2RiZXJydXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjE5MDMsImV4cCI6MjA3MjE5NzkwM30.8s_UPzOeIwxJFR36UTDuTwTSqnAJkIL3rjWeks4dgbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});